# Generated by Django 4.0.3 on 2022-04-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_collections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='cover_image',
            field=models.URLField(default='https://cdn.britannica.com/84/206384-050-00698723/Javan-gliding-tree-frog.jpg', max_length=500),
            preserve_default=False,
        ),
    ]
